/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventarioh.MenuBar.Bienes;
import DB.Bien;
import DB.Propietario;
import inventarioh.MenuBar.Configuracion.AgregarPropietario;
import interfazNueva.menubar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/**
 *
 * @author Usuario
 */
public class Lista_activo extends javax.swing.JFrame {

    //Nueva statement
    public Statement stmt = null;
    //Nuevo ResultSet
    ResultSet rs = null;
    //Variable conexion a la DB
    Connection con = null;
    /**
     * Creates new form Lista_activo
     */
    public Lista_activo(Connection con) throws SQLException{
        initComponents();
        menubar Menu = new menubar(this);
        setJMenuBar(Menu);
        this.con = con;
        
        //Combobox Bienes
        Bien ca = new Bien(con);
        //Se obtienen todas las descripciones de las Bienes
        rs = ca.getAll();
        DefaultListModel list = new DefaultListModel();
        // Anadimos cada una de las categorias al combobox Bienes
        while(rs.next()){
            list.addElement(rs.getString("Codigo")+"-"+rs.getString("Familia")+"        "+rs.getString("Descripcion"));
        } 
        Bienes.setModel(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Bienes = new javax.swing.JList();
        BienPanel = new javax.swing.JPanel();
        CodigoLbl = new javax.swing.JLabel();
        NombreLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProveedorLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Codigolbl = new javax.swing.JLabel();
        Nombrelbl = new javax.swing.JLabel();
        Proveedorlbl = new javax.swing.JLabel();
        Categorialbl = new javax.swing.JLabel();
        Ubicacionlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PrecioRefLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        FechaAdquiLbl = new javax.swing.JLabel();
        EstadosPanel = new javax.swing.JPanel();
        StatusUbiLbl = new javax.swing.JLabel();
        StatusFisicoLbl = new javax.swing.JLabel();
        UbiStatlbl = new javax.swing.JLabel();
        FiscStalbl = new javax.swing.JLabel();
        UsuariosPanel = new javax.swing.JPanel();
        ResponsableLbl = new javax.swing.JLabel();
        Propietario = new javax.swing.JLabel();
        Responsablelbl = new javax.swing.JLabel();
        Propietariolbl = new javax.swing.JLabel();
        Preciolbl = new javax.swing.JLabel();
        Costolbl = new javax.swing.JLabel();
        Fechalbl = new javax.swing.JLabel();
        SalirBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bienes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BienesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Bienes);

        BienPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bien"));

        CodigoLbl.setText("Codigo: ");

        NombreLbl.setText("Nombre: ");

        jLabel3.setText("Categoria:");

        ProveedorLbl.setText("Proveedor:");

        jLabel6.setText("Ubicación:");

        Codigolbl.setText("  ");

        Nombrelbl.setText("  ");

        Proveedorlbl.setText("  ");

        Categorialbl.setText("  ");

        Ubicacionlbl.setText("  ");

        javax.swing.GroupLayout BienPanelLayout = new javax.swing.GroupLayout(BienPanel);
        BienPanel.setLayout(BienPanelLayout);
        BienPanelLayout.setHorizontalGroup(
            BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BienPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addComponent(ProveedorLbl)
                        .addGap(18, 18, 18)
                        .addComponent(Proveedorlbl))
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addComponent(NombreLbl)
                        .addGap(18, 18, 18)
                        .addComponent(Nombrelbl))
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addComponent(CodigoLbl)
                        .addGap(22, 22, 22)
                        .addComponent(Codigolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127)
                .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Ubicacionlbl))
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Categorialbl)))
                .addGap(259, 259, 259))
        );
        BienPanelLayout.setVerticalGroup(
            BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BienPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoLbl)
                            .addComponent(Codigolbl)))
                    .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Categorialbl)))
                .addGap(8, 8, 8)
                .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Ubicacionlbl)))
                    .addGroup(BienPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreLbl)
                            .addComponent(Nombrelbl))))
                .addGap(29, 29, 29)
                .addGroup(BienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProveedorLbl)
                    .addComponent(Proveedorlbl))
                .addGap(22, 22, 22))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        PrecioRefLbl.setText("Precio referencuial:");

        jLabel8.setText("Costo actual:");

        jLabel11.setText("Descripcion:");

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        jScrollPane2.setViewportView(Descripcion);

        FechaAdquiLbl.setText("Fecha de adquisicion:");

        EstadosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Estados"));

        StatusUbiLbl.setText("Ubicación:");

        StatusFisicoLbl.setText("Físico:");

        UbiStatlbl.setText("  ");

        FiscStalbl.setText("  ");

        javax.swing.GroupLayout EstadosPanelLayout = new javax.swing.GroupLayout(EstadosPanel);
        EstadosPanel.setLayout(EstadosPanelLayout);
        EstadosPanelLayout.setHorizontalGroup(
            EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusUbiLbl)
                    .addComponent(StatusFisicoLbl))
                .addGap(18, 18, 18)
                .addGroup(EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FiscStalbl)
                    .addComponent(UbiStatlbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EstadosPanelLayout.setVerticalGroup(
            EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadosPanelLayout.createSequentialGroup()
                .addGroup(EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusUbiLbl)
                    .addComponent(UbiStatlbl))
                .addGap(18, 18, 18)
                .addGroup(EstadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusFisicoLbl)
                    .addComponent(FiscStalbl))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        UsuariosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        ResponsableLbl.setText("Responsable:");

        Propietario.setText("Propietario:");

        Responsablelbl.setText(" ");

        Propietariolbl.setText(" ");

        javax.swing.GroupLayout UsuariosPanelLayout = new javax.swing.GroupLayout(UsuariosPanel);
        UsuariosPanel.setLayout(UsuariosPanelLayout);
        UsuariosPanelLayout.setHorizontalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResponsableLbl)
                    .addComponent(Propietario))
                .addGap(18, 18, 18)
                .addGroup(UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Propietariolbl)
                    .addComponent(Responsablelbl))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        UsuariosPanelLayout.setVerticalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosPanelLayout.createSequentialGroup()
                .addGroup(UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResponsableLbl)
                    .addComponent(Responsablelbl))
                .addGap(18, 18, 18)
                .addGroup(UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Propietario)
                    .addComponent(Propietariolbl))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Preciolbl.setText("  ");

        Costolbl.setText("  ");

        Fechalbl.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FechaAdquiLbl)
                                .addGap(18, 18, 18)
                                .addComponent(Fechalbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrecioRefLbl)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preciolbl)
                                    .addComponent(Costolbl)))))
                    .addComponent(UsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EstadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioRefLbl)
                            .addComponent(Preciolbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Costolbl))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaAdquiLbl)
                            .addComponent(Fechalbl))
                        .addGap(18, 18, 18)
                        .addComponent(UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EstadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        SalirBtn.setText("Salir");
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });

        EditarBtn.setText("Editar");
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EditarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SalirBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditarBtn)
                            .addComponent(SalirBtn))))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(981, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        dispose();
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void BienesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BienesMouseClicked
        if(this.Bienes.getModel().getSize() != 0){//Entra en la condicion si hay mas de un Item en el ComboBox
            //Buscar el id de Categoria con respecto a la descripcion
            Bien cat = new Bien(con);

            //Busqueda de DB, para la categoria seleccionada, y llenar los campos
            String[] parts = this.Bienes.getSelectedValue().toString().split("-");
            String[] space = parts[1].split(" ");
            System.out.println(parts[0] +"/"+ space[0]+"/");
            ResultSet cate = cat.getBien(parts[0],space[0]);
            try {
                this.Codigolbl.setText(cate.getString("codigo"));
                this.Nombrelbl.setText(cate.getString("descripcion"));
                this.Proveedorlbl.setText(cate.getString("proveedor"));
                this.Categorialbl.setText(cate.getString("Familia"));
                this.Ubicacionlbl.setText(cate.getString("con_ubi"));
                this.Preciolbl.setText(cate.getString("Precio_actual"));
                this.Costolbl.setText(cate.getString("Precio_referencial_unitario"));
                this.Fechalbl.setText(cate.getString("Fecha_adquisicion"));
                this.Descripcion.setText(cate.getString("Descripcion_detallada"));
                this.UbiStatlbl.setText(cate.getString("con_ubi"));
                this.FiscStalbl.setText(cate.getString("con_fis"));
                this.Responsablelbl.setText(cate.getString("us_nombre") +" " +cate.getString("us_apellido") );
                this.Propietariolbl.setText(cate.getString("propietario"));

            } catch (SQLException ex) {
                Logger.getLogger(Lista_activo.class.getName()).log(Level.SEVERE, null, ex);
            }

           /* //Cambios graficos al cambiar una categoria
            this.reanudar();*/
        }
    }//GEN-LAST:event_BienesMouseClicked

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
        this.Codigolbl.enable(true);
        this.Nombrelbl.enable(true);
        this.Proveedorlbl.enable(true);
    }//GEN-LAST:event_EditarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_activo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_activo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_activo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_activo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_activo().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BienPanel;
    private javax.swing.JList Bienes;
    private javax.swing.JLabel Categorialbl;
    private javax.swing.JLabel CodigoLbl;
    private javax.swing.JLabel Codigolbl;
    private javax.swing.JLabel Costolbl;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JPanel EstadosPanel;
    private javax.swing.JLabel FechaAdquiLbl;
    private javax.swing.JLabel Fechalbl;
    private javax.swing.JLabel FiscStalbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JLabel Nombrelbl;
    private javax.swing.JLabel PrecioRefLbl;
    private javax.swing.JLabel Preciolbl;
    private javax.swing.JLabel Propietario;
    private javax.swing.JLabel Propietariolbl;
    private javax.swing.JLabel ProveedorLbl;
    private javax.swing.JLabel Proveedorlbl;
    private javax.swing.JLabel ResponsableLbl;
    private javax.swing.JLabel Responsablelbl;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel StatusFisicoLbl;
    private javax.swing.JLabel StatusUbiLbl;
    private javax.swing.JLabel UbiStatlbl;
    private javax.swing.JLabel Ubicacionlbl;
    private javax.swing.JPanel UsuariosPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
