/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventarioh.MenuBar.Configuracion;

import DB.Ubicacion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.Callable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


/**
 *
 * @author Usuario
 */
public class Agregar_ubicacion extends javax.swing.JFrame {
    //Combobox de Ubicacion
    java.awt.List Ubicacion = null;
    //Nuevo ResultSet
    ResultSet rs = null;
    //Variable conexion a la DB
    Connection con = null;
    //Nuevo Callable
    Callable funciones;
    
    int id;
    
    /**
     * Creates new form Ubicacion
     */
    public Agregar_ubicacion(java.awt.List ubicacion, Connection con, Callable hola ) throws SQLException {
        initComponents();
        this.setTitle("Nueva Ubicacion");
        //Le igualamos el combobox de la lista de Ubicacion
        this.Ubicacion = ubicacion;
        //Conexion
        this.con = con;
        //Igualamos las funciones a nuestra variable
        this.funciones = hola;
        //Combobox Ubicacion
        Ubicacion ub = new Ubicacion(con);
        //Se obtienen todas las descripciones de las ubicacion
        rs = ub.getAllid();
        
        if(rs.last()){
            this.id = rs.getInt("idUbicacion") + 1;
            this.idUbicacion.setText(Integer.toString(id));
            this.idUbicacion.setBackground(Color.lightGray);
            this.idUbicacion.setDisabledTextColor(Color.black);
            this.idUbicacion.enable(false);
        }else{
            this.id = 1;
            this.idUbicacion.setText(Integer.toString(id));
            this.idUbicacion.setBackground(Color.lightGray);
            this.idUbicacion.setDisabledTextColor(Color.black);
            this.idUbicacion.enable(false);            
        }
        
        
        
        //Seteamos la Operacion de cierre, a solo esconder este frame
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idUbicacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("(*)Descripcion:");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel2.setText("(*)ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(idUbicacion))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregar)
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(356, 197));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       //Nueva clase Ubicacion
        Ubicacion cat = new Ubicacion(this.con);
        //Si el JtextField esta NO esta vacio
        if(this.descripcion.getText().replaceAll(" ", "").length() != 0){
            //Si se guarda Existosamente en la DB
            if(cat.insertar_ubicacion(this.descripcion.getText().toString(),this.idUbicacion.getText().toString()) ){
                //Mensaje de Exito
                JOptionPane.showMessageDialog(null, "Ubicacion agregada Exitosamente");
                //Buscamos todas las Ubicacion actualizadas
                this.rs  = cat.getAll();
                //Removemos los Items que hay en el JComboBox Ubicacion
                this.Ubicacion.removeAll();
                //A#adimos cada una de las Ubicacion actualizadas al Combobox
                try {
                    while(rs.next()){
                        this.Ubicacion.add(rs.getString("descripcion").toString());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Agregar_ubicacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    //Llamamos a las funciones de borrar y reanudar
                    this.funciones.call();
                    //Ventana actual
                    this.descripcion.setText("");
                    //Se obtienen todas las descripciones de las ubicacion
                    rs = cat.getAllid();

                    if(rs.last()){
                        this.id = rs.getInt("idUbicacion") + 1;
                        this.idUbicacion.setText(Integer.toString(id));
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Agregar_ubicacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                //Mesanje de Error al introducir
                JOptionPane.showMessageDialog(null, "No se agrego la ubicacion.","Error al agregar"
                ,JOptionPane.ERROR_MESSAGE);
            }            
        }else{
            //Mensaje de Error si no estan llenos los campos
            JOptionPane.showMessageDialog(null, "Llenar Todos los Campos (*)","Error al agregar"
                ,JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_ubicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_ubicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_ubicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_ubicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_categoria().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_categoria().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_categoria().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_categoria().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField idUbicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
