/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarioh.MenuBar.Proveedores_Donantes;

import DB.Familia;
import DB.Proveedor;
import inventarioh.MenuBar.Configuracion.AgregarEditar_familia;
import interfazNueva.menubar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.Callable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AgregarEditar_proveedor extends javax.swing.JFrame {
    //Nueva statement
    public Statement stmt = null;
    //Nuevo ResultSet
    ResultSet rs = null;
    //Variable conexion a la DB
    Connection con = null;
    Callable hola = null;
    Callable refrescar = null;
    
    /**
     * Creates new form AgregarEditar_proveedor
     */
    public AgregarEditar_proveedor(Connection con, Callable refrescar) throws SQLException {
        initComponents();
        //Conexion a la DB
        this.con = con;

        stmt = con.createStatement();

        /* Titulo del Jframe */
        this.setTitle("Proveedores");
        //Combobox Categoria
        Proveedor ca = new Proveedor(con);
        //Se obtienen todas las descripciones de las categorias
        rs = ca.getAll();
        this.refrescar = refrescar;     
        // Anadimos cada una de las categorias al combobox Categoria
        while(rs.next()){
            this.Proveedores.add(rs.getString("razon_social"));
        }   
       //Inicializaciones graficas de botones, jtextfields
        /************ Proveedor *************/
            /* Botones */
        this.guardar.setVisible(false);
        this.cancelar.setVisible(false);
            /* Background */
        this.id.setBackground(Color.lightGray);
        this.razon_social.setBackground(Color.lightGray);
        this.rif.setBackground(Color.lightGray);
        this.direccion.setBackground(Color.lightGray);
        this.tlf1.setBackground(Color.lightGray);
        this.tlf2.setBackground(Color.lightGray);
        this.contacto.setBackground(Color.lightGray);
        this.email.setBackground(Color.lightGray);
            /* Color del texto en Disabled */
        this.id.setDisabledTextColor(Color.black);
        this.razon_social.setDisabledTextColor(Color.black);   
        this.rif.setDisabledTextColor(Color.black);
        this.direccion.setDisabledTextColor(Color.black);
        this.tlf1.setDisabledTextColor(Color.black);
        this.tlf2.setDisabledTextColor(Color.black);
        this.contacto.setDisabledTextColor(Color.black);
        this.email.setDisabledTextColor(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Proveedores = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        agregar_proveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        razon_social = new javax.swing.JTextField();
        rif = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        tlf1 = new javax.swing.JTextField();
        tlf2 = new javax.swing.JTextField();
        contacto = new javax.swing.JTextField();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });

        jLabel1.setText("(*)ID:");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        agregar_proveedor.setText("+");
        agregar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_proveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("(*)RIF/Cedula:");

        jLabel6.setText("Proveedores:");

        editar.setText("Editar");
        editar.setPreferredSize(new java.awt.Dimension(71, 23));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion:");

        jLabel4.setText("(*)Razón Social/Nombre:");

        jLabel5.setText("Telefono 2:");

        jLabel7.setText("Email:");

        jLabel8.setText("Contacto:");

        jLabel9.setText("Telefono 1:");

        id.setEnabled(false);

        razon_social.setEnabled(false);

        rif.setEnabled(false);

        direccion.setEnabled(false);

        tlf1.setEnabled(false);

        tlf2.setEnabled(false);

        contacto.setEnabled(false);

        email.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(agregar_proveedor))
                    .addComponent(Proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelar)
                            .addGap(18, 18, 18)
                            .addComponent(guardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tlf2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(agregar_proveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tlf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelar)
                            .addComponent(guardar))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(Proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(725, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        /* Reanudar la seccion de Proveedor a deshabilitado */
    public void reanudar(){
        this.guardar.setVisible(false);
        this.cancelar.setVisible(false);
        this.editar.setVisible(true);
        this.razon_social.setBackground(Color.lightGray);  
        this.rif.setBackground(Color.lightGray);
        this.direccion.setBackground(Color.lightGray);
        this.tlf1.setBackground(Color.lightGray);
        this.tlf2.setBackground(Color.lightGray);
        this.contacto.setBackground(Color.lightGray);
        this.email.setBackground(Color.lightGray);
        
    }
    /* Borrar los JtextFields de Proveedor */
    public void borrarS(){
        this.id.setText("");
        this.razon_social.setText("");
        this.rif.setText("");
        this.direccion.setText("");
        this.tlf1.setText("");
        this.tlf2.setText("");
        this.contacto.setText("");
        this.email.setText("");
    }  
    
    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
        if(this.Proveedores.getItemCount() != 0){//Entra en la condicion si hay mas de un Item en el ComboBox
            //Buscar el id de Categoria con respecto a la descripcion
            Proveedor pro = new Proveedor(con);

            //Busqueda de DB, para la categoria seleccionada, y llenar los campos
            ResultSet proveedor = pro.getProveedor(Proveedores.getSelectedItem().toString());
            try {
                this.id.setText(proveedor.getString("idProveedor"));
                this.razon_social.setText(proveedor.getString("razon_social"));
                this.rif.setText(proveedor.getString("RIF_Cedula"));
                this.direccion.setText(proveedor.getString("direccion"));
                this.tlf1.setText(proveedor.getString("telefono_1"));
                this.tlf2.setText(proveedor.getString("telefono_2"));
                this.contacto.setText(proveedor.getString("persona_contacto"));
                this.email.setText(proveedor.getString("email"));
            } catch (SQLException ex) {
                Logger.getLogger(AgregarEditar_familia.class.getName()).log(Level.SEVERE, null, ex);
            }

            //Cambios graficos al cambiar una categoria
            this.reanudar();
        }
    }//GEN-LAST:event_ProveedoresActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        //Reanudo los campos de Categoria a deshabilitados
        this.reanudar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void agregar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_proveedorActionPerformed
        //Creamos un nueva Callable (Creamos una variable que guarda funciones)
        Callable<Void> prueba = new Callable<Void>() {
            //Funcion call(), la que se ejecutara desde la variable
            public Void call() {
                reanudar();
                borrarS();
                return null;
            }
        };
        //Abrimos un nuevo Jframe para agregar categoria
        Agregar_proveedor pantalla;
        try {
            pantalla = new Agregar_proveedor(this.Proveedores,this.con,prueba,this.refrescar);
            pantalla.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_agregar_proveedorActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        //Si en el Combobox Categorias hay items, la funcion editar servira
        //Habilita los campos de descripcion y los botones de guardar y cancelar
        if(this.Proveedores.getSelectedIndex() != -1){
            this.razon_social.enable(true);
            this.rif.enable(true);
            this.direccion.enable(true);
            this.tlf1.enable(true);
            this.tlf2.enable(true);
            this.contacto.enable(true);
            this.email.enable(true);
            this.guardar.setVisible(true);
            this.cancelar.setVisible(true);
            this.editar.setVisible(false);
            this.razon_social.setBackground(Color.white);
            this.rif.setBackground(Color.white);
            this.direccion.setBackground(Color.white);
            this.tlf1.setBackground(Color.white);
            this.tlf2.setBackground(Color.white);
            this.contacto.setBackground(Color.white);
            this.email.setBackground(Color.white);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        //Clase Proveedor
        Proveedor cat = new Proveedor(con);
        //Si se Guarda la categoria Exitosamente
        if(cat.actualizar_proveedor(this.id.getText().toString(),this.razon_social.getText().toString(),this.rif.getText().toString()
            ,this.direccion.getText().toString(),this.tlf1.getText().toString(),this.tlf2.getText().toString()
            ,this.contacto.getText().toString(),this.email.getText().toString())){
            JOptionPane.showMessageDialog(null, "Proveedor actualizado Exitosamente");
            //Remueve todos los Items del list Proveedor
            this.Proveedores.removeAll();
            //Y se agregan las nuevas categorias al comboBox pero actualizado
            try {
                this.refrescar.call();
                //Nueva Clase Categoria
                Proveedor ca = new Proveedor(con);
                //Se obtienen todas las descripciones de las Proveedor
                rs = ca.getAll();
                // Anadimos cada una de las Proveedor al list Proveedor
                while(rs.next()){
                    this.Proveedores.add(rs.getString("razon_social"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Se borran los campos descripcion y id de Proveedor
            this.borrarS();
            //Se borran los campos 
            this.reanudar();
        }else{
            JOptionPane.showMessageDialog(null, "No se actualizo el proveedor. \n Los campos (*) no pueden repetirse","Error al actualizar"
                ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEditar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEditar_proveedor().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List Proveedores;
    private javax.swing.JButton agregar_proveedor;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField contacto;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField razon_social;
    private javax.swing.JTextField rif;
    private javax.swing.JTextField tlf1;
    private javax.swing.JTextField tlf2;
    // End of variables declaration//GEN-END:variables
}
